os:
  - linux
language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk17
arch:
  - amd64
  - arm64-graviton2
branches:
  only:
    - master

after_success:
- mvn jacoco:report coveralls:report -pl jctools-core
